runtime: python37
env: flexible

env_variables:
  MYSQL_UNIX_SOCKET: "/cloudsql/guideme-bangkitcapstone-01:asia-southeast2:guideme-bangkitcapstone"
  MYSQL_USER: "guideme-bangkitcapstone"
  MYSQL_PASSWORD: "guideme1"
  MYSQL_DB: "GuideMe"
  MYSQL_CURSORCLASS: "DictCursor"
  MYSQL_HOST: "34.101.218.88"
