runtime: python

env_variables:
  MYSQL_UNIX_SOCKET: "/cloudsql/guideme-capstoneproject:asia-southeast2:guideme-bangkitcapstone"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "guideme1"
  MYSQL_DB: "guideme"
  MYSQL_CURSORCLASS: "DictCursor"
  MYSQL_HOST: "34.101.246.136"
