runtime: python37
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  MYSQL_UNIX_SOCKET: "/cloudsql/guideme-bangkitcapstone-01:asia-southeast2:guideme-bangkitcapstone"
  MYSQL_USER: "guideme-bangkitcapstone"
  MYSQL_PASSWORD: "guideme1"
  MYSQL_DB: "GuideMe"
  MYSQL_CURSORCLASS: "DictCursor"
  MYSQL_HOST: "34.101.218.88"
